
-- Exploratory Data Analysis
-- Q1. What is the total revenue generated by Male and Female Customers ?

select gender, sum(purchase_amount) as Revenue
from customer
group by gender ;

-- Q2. Which Customer used a Discount but still spent more than the average purchase ?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > ( select avg(purchase_amount)
								from customer) ;

-- Q3.Which are the top 5 products with the highest average review rating ?

select item_purchased, round(cast(avg(review_rating)as numeric),2) as top_review_rating
from customer
group by item_purchased
order by avg(review_rating) limit 5 ;

-- Q4. Compare the average purchase amount between standard and express shipping ?

select shipping_type, avg(purchase_amount) 
from customer
where shipping_type in ('Express', 'Standard') 
group by shipping_type ;

-- Q5. Do subscribed customers spend more ?
-- Compare average spend and total revenue between subscribers and non subscribers 

select subscription_status,
count(subscription_status),
round(avg(purchase_amount),2),
sum(purchase_amount) as total_purchase_amount
from customer
group by subscription_status ;

-- Q6. Which 5 products have highest percentage of purchases with discount applied ?

select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*), 2) as Discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5 ;

-- Q7. Segment customers into New, Returning and Loyal 
-- based on their total number of prvious purchases and show the count of each segment.

with customer_type as (
	select customer_id, previous_purchases,
    case
		when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal'
        end as customer_segment
	from customer )
select customer_segment, count(*) as 'Number of customers'
from customer_type
group by customer_segment ; 

-- Q8. What are the Top 3 most purchased products within each category
with item_counts as (
select category, item_purchased, count(customer_id) as Total_Orders,
Row_number() over(partition by category 
order by count(customer_id) desc) as item_rank
from customer 
group by category, item_purchased)
select item_rank, category, item_purchased, total_orders 
from item_counts
where item_rank <= 3 ;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

select subscription_status,
count(customer_id) as Repeat_Buyers
from customer 
where previous_purchases > 5
group by subscription_status 
order by Repeat_Buyers desc ;

-- Q10. What is the Revenue Contribution of each age group ?

select age_group, sum(purchase_amount) as Total_amount
from customer 
group by age_group 
order by Total_amount desc ;